services:

  frontend:
    image: ghcr.io/exchanges-lab/statistic/fronted_tv:latest
    container_name: frontend_tv
    networks:
      - cycle
    #ports:
    #  - "8080:80"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    restart: unless-stopped

networks:
  cycle:
    external: true
