services:
  backend:
    image: ghcr.io/exchanges-lab/statistic/backend:v1.2
    container_name: backend
    networks:
      - cycle
    #ports:
    #  - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./storage:/storage
    restart: unless-stopped

networks:
  cycle:
    external: true
